import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Zenvy Partners",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#09090B"
};

import { RestaurantToastProvider } from '@/components/RestaurantToast';
import FetchInterceptor from '@/components/FetchInterceptor';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
        <FetchInterceptor />
        <RestaurantToastProvider>
          <div className="max-w-md mx-auto min-h-screen w-full bg-zinc-950 shadow-2xl relative border-x border-zinc-900 overflow-x-hidden">
            {children}
          </div>
        </RestaurantToastProvider>
      </body>
    </html>
  );
}
